import random
import time
import winsound
from tkinter import *
from tkinter import messagebox

time_gap = input("How frequent you want to receive quotes (time in min): ")

x = [
    "The greatest discovery of my generation is that human beings can alter their lives by altering their attitudes of mind! ...WILLIAM JAMES",
    "You are not what you think you are.But what you think-YOU ARE! ...Dr.NORMAN VINCENT PEALE",
    "Never underestimate your power to change yourself! ...H.JACKSON BROWN, Jr.",
    "A positive attitude is a person's passport to a better tomorrow! ...UNKNOWN",
    "Better keep yourself clean and bright; you are the window through which you must see the world! ...GEORGE BERNARD SHAW",
    "You can't always control circumstances.But you can control your own thoughts! ...CHARLES POPPLESTONE",
    "There is nothing either good or bad, but thinking makes it so! ...WILLIAM SHAKESPEARE",
    "A happy person is not a person in a certain set of circumstances, but rather a person with a certain set of attitudes! ...HUGH DOWNS",
    "Whether you think you can - or think you can't - you are right! ...HENRY FORD",
    "Nurture you mind with great thoughts! ...BENJAMIN",
    "They can because they think they can! ...VIRGIL",
    "What we sincerely believe regarding ourselves is true for us! ...ORISON SWETT MARDEN",
    "You must first clearly see a thing in your mind before you can do it! ...ALEX MORRISON",
    "Imagination is more important than knowledge! ...Albert Einstein",
    "You have control over the pictures that occupy your mind! ...JEFF KELLER",
    "Vision is the art of seeing things invisible to others! ...JONATHAN SWIFT",
    "If you can dream it, you can do it! ...WALT DISNEY",
    "What this power is I cannot say; all I know is that it exists and it becomes available only when a man is in that state of mind in which he knows exactly what he wants and is fully determined not to quit until he finds it! ...ALEXANDER GRAHAM BELL",
    "Effort only fully releases its reward after a person refuses to quit! ...NAPOLEON HILL",
    "With ordinary talent and extra ordinary perseverance, all things are attainable! ...SIR THOMAS BUXTON",
    "Every adversity carries with it the seed of an equivalent ot greater benefit! ...NAPOLEON HILL",
    "No pressure, no diamonds! ...MARY CASE",
    "The thing which hurt, instruct! ...BENJAMIN FRANKLIN",
    "It is a tough road that leads to the heights of greatness! ...SENECCA",
    "Adversity brings out our hidden potential! ...JEFF KELLER",
    "The words you consistently select will shape your destiny! ...ANTHONY ROBBINS",
    "Words are of course, the most powerful drug used by mankind! ...RUDYARD KIPLING",
    "The people who always talk about lack of money generally don't accumulate much of it! ...JEFF KELLER",
    "Choose words that will point you in the direction of your goals! ...JEFF KELLER",
    "A smile is an inexpensive way to improve your looks! ...UNKNOWN",
    "Say you are well, or all is well with you, and God shall hear your words and make them come true! ...ELLA WHEELER WILCOX",
    "The secret of happiness is to count your blessings while others are adding up their troubles! ...WILLIAM PENN",
    "Nothing happens by itself. It all will come your way once you understand that you have to make it come your way, by your own exertions! ...BEN STEIN",
    "A mirror reflects a man's face, but what he is really like is shown by the kind of friends he chooses! ...THE LIVING BIBLE, PROVERB 27",
    "We become part of what we are around! ...UNKNOWN",
    "Good friends are good for health! ...Dr.IRWIN SARASON",
    "Do the thing you fear and the death of fear is certain! ...RALPH WALDO EMERSON",
    "Nothing in life is to be feared. It is only to be understood! ...MARIE CURIE",
    "He who loses wealth loses much; he who loses a friend loses more; but he who loses courage loses all! ...MIGUEL DE CERVANTES",
    "The only way to escape from a prison of fear action! ...JOE TYE",
    "Running away from your fears is a loosing strategy! ...JEFF KELLER",
    "Failure is the only opportunity to more intelligently begin again! ...HENRY FORD",
    "The great mistake a person can make is to be afraid of making one! ...ELBERT HUBBARD",
    "Would you like me to give you a formula for success? It's quite simple. Double your rate of failure! ...THOMAS J.WATSON",
    "You can get everything in life you want if you will just help enough other people get what they want! ...ZIG ZIGLAR",
    "If you are positive and enthusiastic, people will want to spend time with you! ...JEFF KELLER",
    "Getters don't get - givers get! ...EUGENE BENGE",
    "You can succeed best and quickest by helping others to succeed! ...NAPOLEON HILL",
    "Treat every person you encounter with dignity and respect! ...JEFF KELLER",
    "To change your circumstances, first start thinking differently! ...NORMAN VINCENT PEALE",
    "Act as if it were impossible to fail! ...DOROTHEA BRANDE",
    "We cannot solve our problem with the same level of thinking by which we create them! ...ALBERT EINSTEIN",
    "Don't try to memories things hard and more because computer can memorise things hard and more than you - Be Creative, be innovative, be contructive! ...JACK MA",
    "If you can dream it, you can do it! ...JEFF KELLER",
    "The way to get started is to quit talking and begin doing. -Walt Disney",
    "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking. -Steve Jobs",
    "The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. -Oprah Winfrey",
    "The only thing we have to fear is fear itself. -Franklin D. Roosevelt",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. -Martin Luther King Jr.",
    "Do one thing every day that scares you. -Eleanor Roosevelt",
    "Well done is better than well said. -Benjamin Franklin",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. -Helen Keller",
    "It is during our darkest moments that we must focus to see the light. -Aristotle",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. -Ralph Waldo Emerson",
    "Be yourself; everyone else is already taken. -Oscar Wilde",
    "You will face many defeats in life, but never let yourself be defeated. -Maya Angelou",
    "Go confidently in the direction of your dreams! Live the life you've imagined. -Henry David Thoreau",
    "In the end, it's not the years in your life that count. It's the life in your years. -Abraham Lincoln",
    "Never let the fear of striking out keep you from playing the game. -Babe Ruth",
    "In this life we cannot do great things. We can only do small things with great love. -Mother Teresa",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. -Thomas A. Edison",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. -Dr. Seuss",
    "“Life is a succession of lessons which must be lived to be understood.” – Ralph Waldo Emerson",
    "“The only impossible journey is the one you never begin.” – Tony Robbins",
    "“Only a life lived for others is a life worthwhile.” – Albert Einstein",
    "“You only live once, but if you do it right, once is enough.” – Mae West",
    "“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.” – Ralph Waldo Emerson",
    "“Life is really simple, but we insist on making it complicated.” – Confucius",
    "“Life itself is the most wonderful fairy tale.” – Hans Christian Andersen",
    "Life is either a daring adventure or nothing. -Helen Keller",
    "In three words, I can sum up everything I've learned about life: it goes on. -Robert Frost",
    "“Keep smiling, because life is a beautiful thing and there's so much to smile about.” – Marilyn Monroe",
    "“Life is trying things to see if they work.” – Ray Bradbury",
    "Success is not final; failure is not fatal: It is the courage to continue that count. -Winston S. Churchill",
    "Success usually comes to those who are too busy to be looking for it. -Henry David Thoreau",
    "If you want to make your dreams come true, the first thing you have to do is wake up. -J.M. Power",
    "The secret of success is to do the common thing uncommonly well. -John D. Rockefeller Jr.",
    "I find that the harder I work, the more luck I seem to have. -Thomas Jefferson",
    "“Everything you can imagine is real.” – Pablo Picasso",
    "“There are no secrets to success. It is the result of preparation, hard work, and learning from failure.” – Colin Powell",
    "“The only limit to our realization of tomorrow will be our doubts of today.” – Franklin D. Roosevelt",
    "“The road to success and the road to failure are almost exactly the same.” – Colin R. Davis",
    "“Always remember, your focus determines your reality.” – George Lucas",
    "“Try not to become a man of success. Rather become a man of value.” – Albert Einstein",
    "“Don't be afraid to give up the good to go for the great.” – John D. Rockefeller",
    "“Leave nothing for tomorrow which can be done today.” – Abraham Lincoln",
    "“When you undervalue what you do, the world will undervalue who you are.” – Oprah Winfrey",
    "“The only place where success comes before work is in the dictionary.” – Vidal Sassoon",
    "“Before anything else, preparation is the key to success.” – Alexander Graham Bell",
    "“Believe you can, and you're halfway there.” – Theodore Roosevelt",
    "“The only person you are destined to become is the person you decide to be.” – Ralph Waldo Emerson",
    "“I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.” – Maya Angelou",
    "“Winning isn't everything, but wanting to win is.” – Vince Lombardi",
    "“The most difficult thing is the decision to act; the rest is merely tenacity.” – Amelia Earhart",
    "“An unexamined life is not worth living.” – Socrates",
    "“Everything you've ever wanted is on the other side of fear.” – George Addair",
    "“Nothing is impossible, the word itself says, ‘I‘m possible!’” – Audrey Hepburn",
    "“It does not matter how slowly you go as long as you do not stop.” – Confucius",
    "“A man may die, nations may rise and fall, but an idea lives on.” – John F. Kennedy",
    "“I didn't fail the test. I just found 100 ways to do it wrong.” – Benjamin Franklin",
    "“With great power comes great responsibility.” – Stan Lee",
    "“If you look at what you have in life, you‘ll always have more. If you look at what you don’t have in life, you'll never have enough.” – Oprah Winfrey",
    "“Dreaming, after all, is a form of planning.” – Gloria Steinem",
    "“Whatever the mind of man can conceive and believe, it can achieve.” – Napoleon Hill",
    "“First, have a definite, clear, practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends: wisdom, money, materials, and methods. Third, adjust all your means to that end.” – Aristotle",
    "“Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do. So, throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover.” – Mark Twain",
    "When something is important enough, you do it even if the odds are not in your favor. -Elon Musk",
    "If your actions inspire others to dream more, learn more, do more and become more, you are a leader. -John Quincy Adams",
    "Take time to deliberate; but when the time for action arrives, stop thinking and go in. -Andrew Jackson",
    "I'm convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance. -Steve Jobs",
    "“Doing the best at this moment puts you in the best place for the next moment.” – Oprah Winfrey",
    "“You don’t learn to walk by following rules. You learn by doing and by falling over.” – Richard Branson",
    "“High expectations are the key to everything.” – Sam Walton",
    "“The difference between successful people and unsuccessful people is that successful people do all the things unsuccessful people don’t want to do.” – John Paul DeJoria",
    "“The price of inaction is far greater than the cost of a mistake.” – Meg Whitman",
    "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
    "All great achievements require time. -Maya Angelou",
    "Time waits for no one. -Unknown Author",
    "The trouble is, you think you have time. -Jack Kornfield",
    "Either you run the day or the day runs you. -Jim Rohn",
    "“There is never enough time to do everything, but there is always enough time to do the most important thing.” – Brian Tracy",
    "“You may delay, but time will not.” – Benjamin Franklin",
    "“Lack of direction, not lack of time, is the problem. We all have twenty-four-hour days.” – Zig Ziglar",
    "“A goal is a dream with a deadline.” – Napoleon Hill",
    "'The measure of intelligence is the ability to change' -Albert Einstein",
    "'Every day the clock resets. Your wins don't matter. Your failures don't matter. Don't stress on what was, fight for what could be.' -Sean Higgins",
    "'Everyone thinks of changing the world, but no one thinks of changing himself.' -Leo Tolstoy",
    "'Play to your strengths. If you aren’t great at something, do more of what you’re great at.' -Jason Lemkin",
    "'Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.' -Harriet Tubman",
    "“Education is the most powerful weapon which you can use to change the world.” -Nelson Mandela",
    "“The secret of change is to focus all of your energy not on fighting the old, but on building the new” -Socrates",
    "“Since we cannot change reality, let us change the eyes which see reality.” -Nikos Kazantzakis",
    "“There is nothing permanent except change.” -Heraclitus",
    ". “Change is the law of life, and those who look only to the past and present are certain to miss the future” -John F. Kennedy",
    "“If you can’t fly, then run. If you can’t run, then walk. If you can’t walk, then crawl. But whatever you do, you have to keep moving forward” -Martin Luther King Jr.",
    "“If I’d asked my customers what they wanted, they’d have said ‘Don’t change anything.’” -Henry Ford",
    "“Miracles happen every day, change your perception of what a miracle is and you’ll see them all around you.” -Jon Bon Jovi",
    "“Not everything that is faced can be changed, but nothing can be changed until it is faced.” -James Baldwin"]

while True:
    time.sleep(int(time_gap) * 60)
    winsound.Beep(6700, 700)

    messagebox.showinfo(title="REMINDER", message=random.choice(x))
